### PR TITLE
ModelForm now requires either fields or exclude

### PR DESCRIPTION
**Pull request by volksman**

### CODE REVIEW

**Comment by glader** [comment]
Hi. Is this project alive?

**Comment by michaelkuty** [comment]
see #57 @jezdez hasn't time for maintenance
but dbtemplates is still good project which shouldn't die

**Comment by jezdez** [comment]
@glader @michaelkuty Would you like to help out?

**Comment by glader** [comment]
Yes. I have to make pr without pep8 failes?

**Comment by michaelkuty** [comment]
if help means that I merging pull requests and publish new release on pypi, sure !
for this project is important only support for DJ 1.8 and fresh release on pypi - thats all

**Comment by jezdez** [comment]
Added you both to the repo as collaborators, feel free to ping me if you have questions. For the release on PyPI I'd first like to see how you're doing. Many thanks for volunteering!

**Pull request closed without merging**
